<?php
/**
 * TL_ROOT/system/modules/lastlogin/languages/es/modules.php 
 * 
 * Contao Open Source CMS extension: lastlogin 1.8.0 stable 
 * Spanisch translation file 
 * 
 * Copyright : &copy; 2009..2011 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Klaus Bogotz (klabog), klabog 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['lastlogin'] = "Última entrada";
 
?>
