<?php
/**
 * TL_ROOT/system/modules/lastlogin/languages/it/tl_last_login.php 
 * 
 * Contao Open Source CMS extension: lastlogin 1.8.0 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2009..2010 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Paolo Brunelli (PaoloB), http://www.typolightcms.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['last_login']['nobody'] = "Nessuno";
$GLOBALS['TL_LANG']['last_login']['profile'] = "Visualizza profilo";
 
?>
